/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_mg_font_Font */

#ifndef _Included_cz_mg_font_Font
#define _Included_cz_mg_font_Font
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_mg_font_Font
 * Method:    create
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_cz_mg_font_Font_create
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     cz_mg_font_Font
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cz_mg_font_Font_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
