/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_mg_font_FontLibrary */

#ifndef _Included_cz_mg_font_FontLibrary
#define _Included_cz_mg_font_FontLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_mg_font_FontLibrary
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cz_mg_font_FontLibrary_create
  (JNIEnv *, jobject);

/*
 * Class:     cz_mg_font_FontLibrary
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cz_mg_font_FontLibrary_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
